# Generated by Django 6.0.4 on 2026-05-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pdftask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdftask',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='pdftask',
            name='completed_pages',
            field=models.JSONField(default=list),
        ),
    ]
